routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\IklanController;
use App\Http\Controllers\SlideController;
use App\Http\Controllers\MateriController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\PlaylistController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EditprofileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Front End
Route::middleware(['guest'])->group(function(){
    Route::get('/', [FrontendController::class, 'index']);
    Route::get('/detail-artikel/{slug}', [FrontendController::class, 'detail'])->name('detail-artikel');
});
// Front End

// Auth::routes();
Auth::routes(['verify' => true]);
// ADMIN
Route::middleware(['auth'])->group(function(){
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('/kategori', KategoriController::class);
    Route::resource('/artikel', ArtikelController::class);
    Route::resource('/playlist', PlaylistController::class);
    Route::resource('/materi', MateriController::class);
    Route::resource('/slide', SlideController::class);
    Route::resource('/iklan', IklanController::class);
    Route::resource('/profile', EditprofileController::class);
});
// ADMIN

app/Models/Slide.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Slide extends Model
{
    use HasFactory;
    protected $table = 'slide';

    protected $fillable =[
        'judul_slide','link','image','status'
    ];

    protected $hidden= [];
}

app/Http/Controllers/SlideController.php
<?php

namespace App\Http\Controllers;

use App\Models\Slide;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use RealRashid\SweetAlert\Facades\Alert;

class SlideController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $slide = Slide::all();
        return view('back.slide.index', compact('slide'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $slide = Slide::all();
        return view('back.slide.create', compact('slide'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this-> validate($request, [
            'judul_slide' => 'required|min:4',
            'image' => 'mimes:png,jpg,jpeg,gif',
        ]);

        if(!empty($request->file('image'))){

            $data= $request->all();
            $data['image'] = $request->file('image')->store('slidebanner');
            Slide::create($data);

            Alert::success('Success', 'Berhasil Tersimpan!');
        return redirect('/slide');
            // ->with('success', 'Your data has been added!');
        } else {
            $data = $request->all();
            
            Slide::create($data);

            Alert::success('Success', 'Berhasil Tersimpan!');
        return redirect('/slide');
            // ->with('success', 'Your data has been added!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $slide = Slide::find($id);
        $slide->delete();
        Alert::info('Success', 'Berhasil Terhapus');
        return redirect ('/slide');
        // ->with('success', 'Your data has been Deleted!');
    }
}

resources/views/back/slide/create.blade.php
@extends('layouts.default')

@section('content')
<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			
		</div>
	</div>
</div> 
<div class="page-inner mt--5">
<div class="row">
    <div class="col-md-12">
        <div class="card full-height">
            <div class="card-header">
                <div class="card-head-row">
                    <div class="card-title">Form Slide Banner</div>
                    <a class="btn btn-warning btn-sm ml-auto" href="{{route('slide.index')}}">Back</a>
                </div>
            </div>
            <div class="card-body">
                <form action="/slide" method="post" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="judul_slide" class="form-label">Judul Slide</label>
                    <input type="text" value="{{old('judul_slide')}}" name="judul_slide" id="judul_slide" class="form-control">
                </div>
                <div class="form-group">
                    <label for="link" class="form-label">Link</label>
                    <input type="text" value="{{old('link')}}" name="link" id="link" class="form-control">
                </div>
                <div class="form-group">
                    <label for="image" class="form-label">Gambar</label>
                    <input type="file"  name="image"  class="form-control">
                </div>
                <div class="form-group">
                    <label for="status" class="form-label">Status</label>
                    <select name="status" class="form-control">
                    <option value="1">Publish</option>
                    <option value="0">Draft</option>
                    </select>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary btn-sm" type="submit" >Save</button>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@push("script")
<script>
      $('.slide').addClass("active");
</script>
@endpush

resources/views/back/slide/index.blade.php
@extends('layouts.default')

@section('content')
<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			
		</div>
	</div>
</div> 
<div class="page-inner mt--5">
<div class="row">
    <div class="col-md-12">
        <div class="card full-height">
            <div class="card-header">
                <div class="card-head-row">
                    <div class="card-title">Data Slide</div>
                    <a class="btn btn-primary btn-sm ml-auto" href="{{route('slide.create')}}"><i class="fas fa-plus"></i> Create Slide</a>
                </div>
            </div>
            <div class="card-body">
                @if (Session::has('success'))
                    <div class="alert alert-primary">
                        {{Session('success')}}
                    </div>
                @endif
                <div class="table-responsive">
                <table class="table table-bordered">
                    <thead class="table-dark">
                        <tr>
                            <th>ID</th>
                            <th>Judul Slide</th>
                            <th>Link</th>
                            <th>Gambar</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($slide as $row)
                        <tr>
                            <td>{{$row->id}}</td>
                            <td>{{$row->judul_slide}}</td>
                            <td>{{$row->link}}</td>
                            <td>
                                <img src="{{asset('uploads/'.$row->image)}}" width="100">
                            </td>
                            <td>
                                @if ($row->status == '1')
                                    Active
                                @else
                                    Draft
                                @endif
                            </td>
                            <td>
                                {{-- <a class="btn btn-warning btn-sm " href="{{route('slide.edit', $row->id)}}"><i class="far fa-edit"></i></a> --}}
                                <form action="/slide/{{$row->id}}" method="POST" class="d-inline">
                                    @csrf
                                    <input type="hidden" name="_method" value="DELETE">
                                    <button class="btn btn-danger btn-sm" type="submit">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                        @empty
                        <tr>
                            <td colspan="6" class="text-center">Data Tidak Ada</td>
                        </tr>
                        @endforelse
                    </tbody>
                </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push("script")
<script>
      $('.slide').addClass("active");
</script>
@endpush